org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
systemProp.java.net.preferIPv4Stack=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.overridePathCheck=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.resvalues=false
android.enableR8.fullMode=true

kotlin.code.style=official
kotlin.incremental=true
